// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Constellation SDK Code Generator.
//     Generator Version: 1.8.0.16088
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Constellation;
using Constellation.Package;
using System.Threading;
using System.Threading.Tasks;

namespace RemoteControl
{
    /// <summary>
    /// Represents your Constellation
    /// </summary>
	public static class MyConstellation
	{
		/// <summary>
		/// Specifies the sentinels in your Constellation
		/// </summary>
		public enum Sentinels
		{
			/// <summary>
            /// Sentinel 'PC-EMERIC'
            /// </summary>
			[RealName("PC-EMERIC")]
			PC_EMERIC,
		}

		/// <summary>
		/// Specifies the package's instances in your Constellation
		/// </summary>
		public enum PackageInstances
		{
			/// <summary>
            /// Package 'HWMonitor' on 'PC-EMERIC'
            /// </summary>
			[RealName("PC-EMERIC/HWMonitor")]
			PC_EMERIC_HWMonitor,
			/// <summary>
            /// Package 'Pushbullet' on 'PC-EMERIC'
            /// </summary>
			[RealName("PC-EMERIC/Pushbullet")]
			PC_EMERIC_Pushbullet,
		}
		
		/// <summary>
		/// Specifies the packages in your Constellation
		/// </summary>
		public enum Packages
		{
			/// <summary>
            /// Package 'HWMonitor'
            /// </summary>
			[RealName("HWMonitor")]
			HWMonitor,
			/// <summary>
            /// Package 'Pushbullet'
            /// </summary>
			[RealName("Pushbullet")]
			Pushbullet,
		}
    
		/// <summary>
        /// Creates the message scope to the specified sentinel.
        /// </summary>
        /// <param name="sentinel">The sentinel.</param>
        /// <returns>MessageScope</returns>
		public static MessageScope CreateScope(this Sentinels sentinel)
		{
		    return MessageScope.Create(MessageScope.ScopeType.Sentinel, sentinel.GetRealName());
		}    
		
		/// <summary>
        /// Creates the message scope to the specified package's instance.
        /// </summary>
        /// <param name="package">The package's instance.</param>
        /// <returns>MessageScope</returns>
		public static MessageScope CreateScope(this PackageInstances package)
		{
		    return MessageScope.Create(MessageScope.ScopeType.Package, package.GetRealName());      
		} 
		
		/// <summary>
        /// Creates the message scope to the specified package.
        /// </summary>
        /// <param name="package">The package.</param>
        /// <returns>MessageScope</returns>
		public static MessageScope CreateScope(this Packages package)
		{
		    return MessageScope.Create(MessageScope.ScopeType.Package, package.GetRealName());        
		}
	}
	
	/// <summary>
    /// Specifies the real name of an enum value.
    /// </summary>
    /// <seealso cref="System.Attribute" />
	[System.AttributeUsage(System.AttributeTargets.Field)]
	public class RealNameAttribute : System.Attribute
	{
	    /// <summary>
        /// Gets or sets the real name.
        /// </summary>
        /// <value>
        /// The real name.
        /// </value>
		public System.String RealName { get; set; }

		/// <summary>
        /// Initializes a new instance of the <see cref="RealNameAttribute"/> class.
        /// </summary>
        /// <param name="realname">The real name.</param>
		public RealNameAttribute(System.String realname)
		{
			this.RealName = realname;
		}
		
	    /// <summary>
        /// Gets the real name of an enum value.
        /// </summary>
        /// <typeparam name="TEnum">The type of the enum.</typeparam>
        /// <param name="value">The enum value.</param>
        /// <returns>The real name.</returns>
		public static string GetRealName<TEnum>(TEnum value)
		{
			var memInfo = typeof(TEnum).GetMember(value.ToString());
			var attributes = memInfo[0].GetCustomAttributes(typeof(RealNameAttribute), false);
			return (attributes != null && attributes.Length > 0) ? ((RealNameAttribute)attributes[0]).RealName : value.ToString();
		}
	}

	/// <summary>
    /// Provides extension methods to get the real name of a Sentinel, Package or PackageInstance.
    /// </summary>
	public static class RealNameExtension
	{
		public static string GetRealName(this MyConstellation.Sentinels sentinel)
		{
			return RealNameAttribute.GetRealName<MyConstellation.Sentinels>(sentinel);
		}

		public static string GetRealName(this MyConstellation.Packages package)
		{
			return RealNameAttribute.GetRealName<MyConstellation.Packages>(package);
		}

		public static string GetRealName(this MyConstellation.PackageInstances package)
		{
			return RealNameAttribute.GetRealName<MyConstellation.PackageInstances>(package);
		}
	}
}

namespace RemoteControl.HWMonitor.StateObjects
{
	/// <summary>
	/// Specifies the know StateObjects for the package HWMonitor
	/// </summary>
	public enum HWMonitorStateObjectNames
	{
		/// <summary>
		/// StateObject '/hdd/1/load/0'
		/// </summary>
		[RealName("/hdd/1/load/0")]
        _hdd_1_load_0,
		/// <summary>
		/// StateObject '/intelcpu/0/clock/4'
		/// </summary>
		[RealName("/intelcpu/0/clock/4")]
        _intelcpu_0_clock_4,
		/// <summary>
		/// StateObject '/intelcpu/0/power/2'
		/// </summary>
		[RealName("/intelcpu/0/power/2")]
        _intelcpu_0_power_2,
		/// <summary>
		/// StateObject '/intelcpu/0/power/3'
		/// </summary>
		[RealName("/intelcpu/0/power/3")]
        _intelcpu_0_power_3,
		/// <summary>
		/// StateObject '/intelcpu/0/power/0'
		/// </summary>
		[RealName("/intelcpu/0/power/0")]
        _intelcpu_0_power_0,
		/// <summary>
		/// StateObject '/intelcpu/0/power/1'
		/// </summary>
		[RealName("/intelcpu/0/power/1")]
        _intelcpu_0_power_1,
		/// <summary>
		/// StateObject '/ram/load/0'
		/// </summary>
		[RealName("/ram/load/0")]
        _ram_load_0,
		/// <summary>
		/// StateObject '/intelcpu/0/clock/0'
		/// </summary>
		[RealName("/intelcpu/0/clock/0")]
        _intelcpu_0_clock_0,
		/// <summary>
		/// StateObject '/nvidiagpu/0/clock/2'
		/// </summary>
		[RealName("/nvidiagpu/0/clock/2")]
        _nvidiagpu_0_clock_2,
		/// <summary>
		/// StateObject '/intelcpu/0/clock/1'
		/// </summary>
		[RealName("/intelcpu/0/clock/1")]
        _intelcpu_0_clock_1,
		/// <summary>
		/// StateObject '/intelcpu/0/clock/2'
		/// </summary>
		[RealName("/intelcpu/0/clock/2")]
        _intelcpu_0_clock_2,
		/// <summary>
		/// StateObject '/intelcpu/0/clock/3'
		/// </summary>
		[RealName("/intelcpu/0/clock/3")]
        _intelcpu_0_clock_3,
		/// <summary>
		/// StateObject '/nic/23/datarate/1'
		/// </summary>
		[RealName("/nic/23/datarate/1")]
        _nic_23_datarate_1,
		/// <summary>
		/// StateObject '/nic/23/datarate/0'
		/// </summary>
		[RealName("/nic/23/datarate/0")]
        _nic_23_datarate_0,
		/// <summary>
		/// StateObject '/ram/data/0'
		/// </summary>
		[RealName("/ram/data/0")]
        _ram_data_0,
		/// <summary>
		/// StateObject '/ram/data/1'
		/// </summary>
		[RealName("/ram/data/1")]
        _ram_data_1,
		/// <summary>
		/// StateObject '/nic/1/datarate/2'
		/// </summary>
		[RealName("/nic/1/datarate/2")]
        _nic_1_datarate_2,
		/// <summary>
		/// StateObject '/nic/1/datarate/1'
		/// </summary>
		[RealName("/nic/1/datarate/1")]
        _nic_1_datarate_1,
		/// <summary>
		/// StateObject '/nic/1/datarate/0'
		/// </summary>
		[RealName("/nic/1/datarate/0")]
        _nic_1_datarate_0,
		/// <summary>
		/// StateObject '/hdd/0/data/2'
		/// </summary>
		[RealName("/hdd/0/data/2")]
        _hdd_0_data_2,
		/// <summary>
		/// StateObject 'Hardware'
		/// </summary>
		[RealName("Hardware")]
        Hardware,
		/// <summary>
		/// StateObject '/hdd/0/data/1'
		/// </summary>
		[RealName("/hdd/0/data/1")]
        _hdd_0_data_1,
		/// <summary>
		/// StateObject '/hdd/0'
		/// </summary>
		[RealName("/hdd/0")]
        _hdd_0,
		/// <summary>
		/// StateObject '/hdd/0/level/0'
		/// </summary>
		[RealName("/hdd/0/level/0")]
        _hdd_0_level_0,
		/// <summary>
		/// StateObject '/intelcpu/0/load/2'
		/// </summary>
		[RealName("/intelcpu/0/load/2")]
        _intelcpu_0_load_2,
		/// <summary>
		/// StateObject '/intelcpu/0/load/1'
		/// </summary>
		[RealName("/intelcpu/0/load/1")]
        _intelcpu_0_load_1,
		/// <summary>
		/// StateObject '/intelcpu/0/load/4'
		/// </summary>
		[RealName("/intelcpu/0/load/4")]
        _intelcpu_0_load_4,
		/// <summary>
		/// StateObject '/nic/0/datarate/2'
		/// </summary>
		[RealName("/nic/0/datarate/2")]
        _nic_0_datarate_2,
		/// <summary>
		/// StateObject '/nic/0/datarate/1'
		/// </summary>
		[RealName("/nic/0/datarate/1")]
        _nic_0_datarate_1,
		/// <summary>
		/// StateObject '/nic/0/datarate/0'
		/// </summary>
		[RealName("/nic/0/datarate/0")]
        _nic_0_datarate_0,
		/// <summary>
		/// StateObject '/nic/3/datarate/2'
		/// </summary>
		[RealName("/nic/3/datarate/2")]
        _nic_3_datarate_2,
		/// <summary>
		/// StateObject '/nic/3/datarate/1'
		/// </summary>
		[RealName("/nic/3/datarate/1")]
        _nic_3_datarate_1,
		/// <summary>
		/// StateObject '/nic/3/datarate/0'
		/// </summary>
		[RealName("/nic/3/datarate/0")]
        _nic_3_datarate_0,
		/// <summary>
		/// StateObject '/nvidiagpu/0/load/2'
		/// </summary>
		[RealName("/nvidiagpu/0/load/2")]
        _nvidiagpu_0_load_2,
		/// <summary>
		/// StateObject '/nvidiagpu/0/load/3'
		/// </summary>
		[RealName("/nvidiagpu/0/load/3")]
        _nvidiagpu_0_load_3,
		/// <summary>
		/// StateObject '/nvidiagpu/0/load/0'
		/// </summary>
		[RealName("/nvidiagpu/0/load/0")]
        _nvidiagpu_0_load_0,
		/// <summary>
		/// StateObject '/nvidiagpu/0/load/1'
		/// </summary>
		[RealName("/nvidiagpu/0/load/1")]
        _nvidiagpu_0_load_1,
		/// <summary>
		/// StateObject '/intelcpu/0/load/0'
		/// </summary>
		[RealName("/intelcpu/0/load/0")]
        _intelcpu_0_load_0,
		/// <summary>
		/// StateObject '/hdd/0/load/0'
		/// </summary>
		[RealName("/hdd/0/load/0")]
        _hdd_0_load_0,
		/// <summary>
		/// StateObject '/hdd/1'
		/// </summary>
		[RealName("/hdd/1")]
        _hdd_1,
		/// <summary>
		/// StateObject '/intelcpu/0/load/3'
		/// </summary>
		[RealName("/intelcpu/0/load/3")]
        _intelcpu_0_load_3,
		/// <summary>
		/// StateObject '/nvidiagpu/0/clock/0'
		/// </summary>
		[RealName("/nvidiagpu/0/clock/0")]
        _nvidiagpu_0_clock_0,
		/// <summary>
		/// StateObject '/hdd/1/temperature/0'
		/// </summary>
		[RealName("/hdd/1/temperature/0")]
        _hdd_1_temperature_0,
		/// <summary>
		/// StateObject '/hdd/0/temperature/0'
		/// </summary>
		[RealName("/hdd/0/temperature/0")]
        _hdd_0_temperature_0,
		/// <summary>
		/// StateObject '/nvidiagpu/0/clock/1'
		/// </summary>
		[RealName("/nvidiagpu/0/clock/1")]
        _nvidiagpu_0_clock_1,
		/// <summary>
		/// StateObject '/intelcpu/0/temperature/4'
		/// </summary>
		[RealName("/intelcpu/0/temperature/4")]
        _intelcpu_0_temperature_4,
		/// <summary>
		/// StateObject '/nic/23/datarate/2'
		/// </summary>
		[RealName("/nic/23/datarate/2")]
        _nic_23_datarate_2,
		/// <summary>
		/// StateObject '/intelcpu/0/temperature/2'
		/// </summary>
		[RealName("/intelcpu/0/temperature/2")]
        _intelcpu_0_temperature_2,
		/// <summary>
		/// StateObject '/intelcpu/0/temperature/3'
		/// </summary>
		[RealName("/intelcpu/0/temperature/3")]
        _intelcpu_0_temperature_3,
		/// <summary>
		/// StateObject '/intelcpu/0/temperature/0'
		/// </summary>
		[RealName("/intelcpu/0/temperature/0")]
        _intelcpu_0_temperature_0,
		/// <summary>
		/// StateObject '/intelcpu/0/temperature/1'
		/// </summary>
		[RealName("/intelcpu/0/temperature/1")]
        _intelcpu_0_temperature_1,
	}

	/// <summary>
    /// Provides extension methods to get the real name of a HWMonitorStateObjectNames.
    /// </summary>
	public static class HWMonitorStateObjectNamesExtension
	{
		public static string GetRealName(this HWMonitorStateObjectNames stateObjectName)
		{
			return RealNameAttribute.GetRealName<HWMonitorStateObjectNames>(stateObjectName);
		}
	}

    /// <summary>
    ///  Specifies that the property is attach to HWMonitor's StateObject.
    /// </summary>
    /// <seealso cref="Constellation.Package.StateObjectLinkAttribute" />
    public class HWMonitorStateObjectLinkAttribute : StateObjectLinkAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HWMonitorStateObjectLinkAttribute"/> class.
        /// </summary>
        /// <param name="name">The StateObject name.</param>
        public HWMonitorStateObjectLinkAttribute() : base()
        {
            this.Package = MyConstellation.Packages.HWMonitor.GetRealName();
        }

		/// <summary>
        /// Initializes a new instance of the <see cref="HWMonitorStateObjectLinkAttribute"/> class.
        /// </summary>
        /// <param name="sentinel">The sentinel.</param>
        public HWMonitorStateObjectLinkAttribute(MyConstellation.Sentinels sentinel) : this()
        { 
			this.Sentinel = sentinel.GetRealName();
		}

        /// <summary>
        /// Initializes a new instance of the <see cref="HWMonitorStateObjectLinkAttribute"/> class.
        /// </summary>
        /// <param name="name">The StateObject name.</param>
        public HWMonitorStateObjectLinkAttribute(HWMonitorStateObjectNames name)
            : base(MyConstellation.Packages.HWMonitor.GetRealName(), name.GetRealName())
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="HWMonitorStateObjectLinkAttribute"/> class.
        /// </summary>
        /// <param name="sentinel">The sentinel.</param>
        /// <param name="name">The StateObject name.</param>
        public HWMonitorStateObjectLinkAttribute(MyConstellation.Sentinels sentinel, HWMonitorStateObjectNames name)
            : base(sentinel.GetRealName(), MyConstellation.Packages.HWMonitor.GetRealName(), name.GetRealName())
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="HWMonitorStateObjectLinkAttribute"/> class.
        /// </summary>
        /// <param name="sentinel">The sentinel.</param>
        /// <param name="name">The StateObject name.</param>
        /// <param name="type">The StateObject type.</param>
        public HWMonitorStateObjectLinkAttribute(MyConstellation.Sentinels sentinel, HWMonitorStateObjectNames name, string type)
            : base(sentinel.GetRealName(), MyConstellation.Packages.HWMonitor.GetRealName(), name.GetRealName(), type)
        { }
    }

}



namespace RemoteControl.PushBullet.MessageCallbacks
{
	/// <summary>
	/// Type 'SendPushRequest'
	/// </summary>
	public class SendPushRequest 
	{
		/// <summary>
		/// The Iden.
		/// </summary>
		public System.String Iden { get; set; }

		/// <summary>
		/// The Title.
		/// </summary>
		public System.String Title { get; set; }

		/// <summary>
		/// The Message.
		/// </summary>
		public System.String Message { get; set; }

	}

	/// <summary>
	/// Provides extension methods for the MessageScope to PushBullet
	/// </summary>
	public static class PushBulletExtensions
	{
		/// <summary>
		/// Create a PushBulletScope
		/// </summary>
		/// <param name="scope">The Constellation MessageScope</param>
		public static PushBulletScope ToPushBulletScope(this MessageScope scope)
		{
			return new PushBulletScope(scope);
		}

		/// <summary>
		/// Create a PushBulletScope to all packages of the specified sentinel
		/// </summary>
		/// <param name="sentinel">The sentinel</param>
		public static PushBulletScope CreatePushBulletScope(this RemoteControl.MyConstellation.Sentinels sentinel)
		{
		    return MessageScope.Create(MessageScope.ScopeType.Sentinel, sentinel.GetRealName()).ToPushBulletScope();        
		}
		
		/// <summary>
		/// Create a PushBulletScope to a specific package
		/// </summary>
		/// <param name="package">The package</param>
		public static PushBulletScope CreatePushBulletScope(this RemoteControl.MyConstellation.PackageInstances package)
		{
		    return MessageScope.Create(MessageScope.ScopeType.Package, package.GetRealName()).ToPushBulletScope();        
		}
		
		/// <summary>
		/// Create a PushBulletScope to a specific package
		/// </summary>
		/// <param name="package">The package</param>
		public static PushBulletScope CreatePushBulletScope(this RemoteControl.MyConstellation.Packages package)
		{
		    return MessageScope.Create(MessageScope.ScopeType.Package, package.GetRealName()).ToPushBulletScope();  
		}
	}

	/// <summary>
    /// Represent a message scope to PushBullet
    /// </summary>
	public class PushBulletScope
	{
        /// <summary>
        /// The current scope
        /// </summary>
		private MessageScope currentScope = null;

		/// <summary>
        /// Initializes a new instance of the <see cref="PushBulletScope"/> class.
        /// </summary>
        /// <param name="scope">The scope.</param>
		public PushBulletScope(MessageScope scope)
		{
			this.currentScope = scope;
		}

		/// <summary>
		/// Send message 'SendPush' to the current scope
		/// </summary>
		/// <param name="request">The 'request' parameter</param>
		public void SendPush(SendPushRequest request)
		{
			this.currentScope.GetProxy().SendPush(request);
		}
	}
}
